name: gizlialan
description: >
  GizliAlan — personal Hidden Space vault for Demirhan.
  Privacy-first local notes & files. No spyware, no cloud, no SMS intercept.
publish_to: "none"
version: 0.4.2+8

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  local_auth: ^3.0.2
  image_picker: ^1.2.3
  file_picker: ^13.1.0
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  cryptography: ^2.9.0
  cryptography_flutter: ^2.3.4
  crypto: ^3.0.6
  intl: ^0.20.2
  path: ^1.9.0
  uuid: ^4.5.1
  webview_flutter: ^4.14.1
  webview_flutter_android: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/wallpapers/default.jpg
