#!/usr/bin/env python3
"""Generates the original "Hesap Makinesi / Calculator" launcher icon.

One geometry, three outputs (keeps vector and PNGs identical):
  * adaptive icon foreground + monochrome vector drawables (API 26+/33+)
  * legacy/round PNG mipmaps (fallback)
  * 512x512 Play Store icon (docs/store_icon_512.png)

Design: a plain light calculator body with a dark display and a 3x3 key
grid, the bottom-right "=" key in the app's mint accent, on a deep navy
background. Drawn from scratch; not based on any vendor's calculator icon.
Run: python3 tool/gen_launcher_icon.py (needs Pillow).
"""
import os
from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, 'android', 'app', 'src', 'main', 'res')

BG = '#10263A'
BODY = '#E8EEF3'
DISPLAY = '#16324A'
DIGITS = '#7CFFB2'
KEY = '#A9B8C8'
OP_KEY = '#5E7890'
EQ_KEY = '#2FC57E'
EQ_BARS = '#FFFFFF'

# Geometry in the 108x108 adaptive-icon viewport (safe zone: r=33 circle).
BODY_R = (36, 29, 36, 50, 7)          # x, y, w, h, radius
DISPLAY_R = (40, 33, 28, 11, 3)
DIGIT_BAR = (55, 37.5, 9, 3, 1.5)
KEY_SIZE, KEY_GAP, KEY_X0, KEY_Y0, KEY_RAD = 7, 3.5, 40, 48, 2


def keys():
    out = []
    for row in range(3):
        for col in range(3):
            x = KEY_X0 + col * (KEY_SIZE + KEY_GAP)
            y = KEY_Y0 + row * (KEY_SIZE + KEY_GAP)
            if row == 2 and col == 2:
                kind = 'eq'
            elif col == 2:
                kind = 'op'
            else:
                kind = 'key'
            out.append((x, y, kind))
    return out


def eq_bars(x, y):
    # two short horizontal bars centred in the "=" key
    return [(x + 1.75, y + 2.0, 3.5, 1.0, 0.5), (x + 1.75, y + 4.0, 3.5, 1.0, 0.5)]


def fmt(v):
    return ('%.2f' % v).rstrip('0').rstrip('.')


def rrect_path(x, y, w, h, r):
    f = fmt
    return (f'M{f(x + r)},{f(y)}H{f(x + w - r)}A{f(r)},{f(r)} 0,0 1 {f(x + w)},{f(y + r)}'
            f'V{f(y + h - r)}A{f(r)},{f(r)} 0,0 1 {f(x + w - r)},{f(y + h)}'
            f'H{f(x + r)}A{f(r)},{f(r)} 0,0 1 {f(x)},{f(y + h - r)}'
            f'V{f(y + r)}A{f(r)},{f(r)} 0,0 1 {f(x + r)},{f(y)}Z')


def vector(paths):
    body = '\n'.join(
        f'    <path\n        android:fillColor="{c}"\n'
        + (f'        android:fillType="{ft}"\n' if ft else '')
        + f'        android:pathData="{d}" />'
        for c, d, ft in paths)
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by tool/gen_launcher_icon.py - original design. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp"\n    android:height="108dp"\n'
            '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
            f'{body}\n</vector>\n')


def write_vectors():
    colors = {'key': KEY, 'op': OP_KEY, 'eq': EQ_KEY}
    fg = [(BODY, rrect_path(*BODY_R), None), (DISPLAY, rrect_path(*DISPLAY_R), None),
          (DIGITS, rrect_path(*DIGIT_BAR), None)]
    for x, y, kind in keys():
        fg.append((colors[kind], rrect_path(x, y, KEY_SIZE, KEY_SIZE, KEY_RAD), None))
        if kind == 'eq':
            for b in eq_bars(x, y):
                fg.append((EQ_BARS, rrect_path(*b), None))
    os.makedirs(os.path.join(RES, 'drawable'), exist_ok=True)
    with open(os.path.join(RES, 'drawable', 'ic_launcher_foreground.xml'), 'w') as fh:
        fh.write(vector(fg))

    # Monochrome (themed icons): body outline + display + keys, alpha only.
    bx, by, bw, bh, br = BODY_R
    ring = rrect_path(bx, by, bw, bh, br) + rrect_path(bx + 2.5, by + 2.5, bw - 5, bh - 5, br - 2)
    mono = [('#FFFFFFFF', ring, 'evenOdd'), ('#FFFFFFFF', rrect_path(*DISPLAY_R), None)]
    for x, y, _ in keys():
        mono.append(('#FFFFFFFF', rrect_path(x, y, KEY_SIZE, KEY_SIZE, KEY_RAD), None))
    with open(os.path.join(RES, 'drawable', 'ic_launcher_monochrome.xml'), 'w') as fh:
        fh.write(vector(mono))


def render(px, mask):
    """Renders the visible 72dp area (18..90 of the viewport) at px size."""
    ss = 4
    size = px * ss
    s = size / 72.0

    def box(x, y, w, h, r):
        return ([(x - 18) * s, (y - 18) * s, (x - 18 + w) * s, (y - 18 + h) * s], r * s)

    img = Image.new('RGBA', (size, size), BG)
    d = ImageDraw.Draw(img)
    for spec, col in [(BODY_R, BODY), (DISPLAY_R, DISPLAY), (DIGIT_BAR, DIGITS)]:
        b, r = box(*spec)
        d.rounded_rectangle(b, r, fill=col)
    colors = {'key': KEY, 'op': OP_KEY, 'eq': EQ_KEY}
    for x, y, kind in keys():
        b, r = box(x, y, KEY_SIZE, KEY_SIZE, KEY_RAD)
        d.rounded_rectangle(b, r, fill=colors[kind])
        if kind == 'eq':
            for bar in eq_bars(x, y):
                bb, rr = box(*bar)
                d.rounded_rectangle(bb, rr, fill=EQ_BARS)
    if mask:
        m = Image.new('L', (size, size), 0)
        md = ImageDraw.Draw(m)
        if mask == 'circle':
            md.ellipse([0, 0, size - 1, size - 1], fill=255)
        else:
            md.rounded_rectangle([0, 0, size - 1, size - 1], size * 0.22, fill=255)
        img.putalpha(m)
    return img.resize((px, px), Image.LANCZOS)


def main():
    write_vectors()
    for density, px in [('mdpi', 48), ('hdpi', 72), ('xhdpi', 96), ('xxhdpi', 144), ('xxxhdpi', 192)]:
        folder = os.path.join(RES, f'mipmap-{density}')
        os.makedirs(folder, exist_ok=True)
        render(px, 'square').save(os.path.join(folder, 'ic_launcher.png'), optimize=True)
        render(px, 'circle').save(os.path.join(folder, 'ic_launcher_round.png'), optimize=True)
    render(512, None).convert('RGB').save(os.path.join(ROOT, 'docs', 'store_icon_512.png'), optimize=True)


if __name__ == '__main__':
    main()
